### ISSUE TITLE
山东大学相对封闭管控的官方文件

### ISSUE THREAD

**Issue by Batheinautumnwind** [tonysyz/SDUlockdown#1]
文件都是学校官方文件，证实了管控举措属实
[郭新立在会议上的讲话.pdf](https://github.com/tonysyz/SDUlockdown/files/8695525/default.pdf)
[山东大学校园由封闭管理向相对封闭管理转换 疫情防控工作方案.pdf](https://github.com/tonysyz/SDUlockdown/files/8695526/default.pdf)

**Comment by tonysyz** [comment]
Files added to /log/
